version: "3.8"
services:
  yumdownloader:
    build: 
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./rpm
        target: /rpm
      - type: bind
        source: ./downloaded
        target: /downloaded
    environment: 
      - PACKAGES=